@inspect! r(3, 4) + r(3, 4)
@inspect! r(3, 4) - r(3, 4)
@inspect! r(3, 4) * r(4, 3)
@inspect! r(3, 4) / r(3, 4)

@inspect! abs.(X)
@inspect! acos.(X)
@inspect! asin.(X)
@inspect! atan.(X)
@inspect! batched_mul(r(3, 4, 5), r(4, 3))
@inspect! cbrt.(X)
@inspect! clamp.(X, 0.2, 0.4)
@inspect! NNlib.conv(r(10, 10, 3, 1), r(3, 3, 3, 6))
# @inspect! cumsum(X; dims=1)  -- need keyword support
@inspect! exp.(X)
# gather - figure out example
@inspect! log.(X)
@inspect! maximum(X)
@inspect! minimum(X)
@inspect! reduce(+, X)
@inspect! reshape(X, 4, 3)
@inspect! reverse(r(5))
# scatter - figure out exampl
@inspect! sin.(X)
@inspect! sqrt(r(3, 3))
@inspect! sqrt.(r(3, 4))
@inspect! tan.(X)
@inspect! transpose(X)

@inspect! softmax(rand(3, 4))